// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_5hQkCIolMNAeSyfihH3tFLrNtuuYo8w',
    appId: '1:458891563022:web:bef60b03a7ee9bc37eac5f',
    messagingSenderId: '458891563022',
    projectId: 'micro-4b90c',
    authDomain: 'micro-4b90c.firebaseapp.com',
    storageBucket: 'micro-4b90c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkRtic3BbMpoSN__Vl5a143O826fgU-xM',
    appId: '1:458891563022:android:a3e68b55f5b3f6237eac5f',
    messagingSenderId: '458891563022',
    projectId: 'micro-4b90c',
    storageBucket: 'micro-4b90c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9o-8Vl4fnQ-TUxx7ZuukATDl5nPqFCAM',
    appId: '1:458891563022:ios:c84a609a2d8fc5857eac5f',
    messagingSenderId: '458891563022',
    projectId: 'micro-4b90c',
    storageBucket: 'micro-4b90c.appspot.com',
    iosBundleId: 'com.example.micro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9o-8Vl4fnQ-TUxx7ZuukATDl5nPqFCAM',
    appId: '1:458891563022:ios:c84a609a2d8fc5857eac5f',
    messagingSenderId: '458891563022',
    projectId: 'micro-4b90c',
    storageBucket: 'micro-4b90c.appspot.com',
    iosBundleId: 'com.example.micro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_5hQkCIolMNAeSyfihH3tFLrNtuuYo8w',
    appId: '1:458891563022:web:8f333ee0d080bd2c7eac5f',
    messagingSenderId: '458891563022',
    projectId: 'micro-4b90c',
    authDomain: 'micro-4b90c.firebaseapp.com',
    storageBucket: 'micro-4b90c.appspot.com',
  );
}
